version: '3.7'

services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile.prod

    # setting --workers=2 or more does something funky with Dash. I'm guessing it spreads the outputs across
    # different workers and the dependency map gets out of whack. (throws key errors for chart not found in dict)
    command: gunicorn --threads=4 --worker-class=gthread --bind 0.0.0.0:5000 manage:run_app()

    ports:
      - 5000:5000
    env_file:
      - ./.env.prod
